### PR TITLE
chore: prune accessible repos for advisories identity

### PR DESCRIPTION
**Pull request by luhring**
x-ref: https://github.com/chainguard-dev/enterprise-advisories/pull/527#issuecomment-1913738736

### CODE REVIEW

**Review by mattmoor — APPROVED** [review]
Hmm, if all we need is `enterprise-packages` then we should probably shift this to a trust policy in enterprise-packages 🤔 

Let's merge this and see, but if it works with just this, we should shuffle things around a bit more.

**Comment by luhring** [comment]
> Let's merge this and see, but if it works with just this, we should shuffle things around a bit more.

It seems to be working well, btw. Let me know what's next here 🖖

**Comment by mattmoor** [comment]
We should just be able to move this policy into `enterprise-packages` and `chainguard-dev` -> `chainguard-dev/enterprise-packages` in the `scope` for `octo-sts-action`.

**Comment by mattmoor** [comment]
Drop `repositories:` in `enterprise-packages`, it's not allowed in repo-level trust policies

**Pull request merged**
